; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35222.0 

include listing.inc

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	_Avx2WmemEnabledWeakValue
;	COMDAT _Avx2WmemEnabledWeakValue
_BSS	SEGMENT
_Avx2WmemEnabledWeakValue DD 01H DUP (?)
_BSS	ENDS
PUBLIC	scalar_subtract
PUBLIC	packet_subtract
PUBLIC	eigen_subtract
PUBLIC	??$dot@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@?$MatrixBase@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@Eigen@@QEBANAEBV01@@Z ; Eigen::MatrixBase<Eigen::Map<Eigen::Matrix<double,-1,1,0,-1,1> const ,0,Eigen::Stride<0,0> > >::dot<Eigen::Map<Eigen::Matrix<double,-1,1,0,-1,1> const ,0,Eigen::Stride<0,0> > >
PUBLIC	packet4_subtract
PUBLIC	scan_two_pass
PUBLIC	scan_fused
PUBLIC	__real@bff0000000000000
PUBLIC	__xmm@7fefffffffffffff7fefffffffffffff
PUBLIC	__xmm@7fffffffffffffff7fffffffffffffff
PUBLIC	__xmm@80000000000000008000000000000000
EXTRN	_dclass:PROC
EXTRN	_fltused:DWORD
;	COMDAT pdata
pdata	SEGMENT
$pdata$?fpclassify@@YAHN@Z DD imagerel $LN6
	DD	imagerel $LN6+15
	DD	imagerel $unwind$?fpclassify@@YAHN@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?finite_max_abs@detail@linalg@kibo@@YA_NPEBN_KAEAN@Z DD imagerel $LN49
	DD	imagerel $LN49+261
	DD	imagerel $unwind$?finite_max_abs@detail@linalg@kibo@@YA_NPEBN_KAEAN@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?contiguous_dot@detail@linalg@kibo@@YANPEBN0_KN@Z DD imagerel $LN37
	DD	imagerel $LN37+283
	DD	imagerel $unwind$?contiguous_dot@detail@linalg@kibo@@YANPEBN0_KN@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$packet_subtract DD imagerel $LN36
	DD	imagerel $LN36+289
	DD	imagerel $unwind$packet_subtract
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$eigen_subtract DD imagerel $LN362
	DD	imagerel $LN362+355
	DD	imagerel $unwind$eigen_subtract
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$1$eigen_subtract DD imagerel $LN362+355
	DD	imagerel $LN362+494
	DD	imagerel $chain$1$eigen_subtract
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$2$eigen_subtract DD imagerel $LN362+494
	DD	imagerel $LN362+799
	DD	imagerel $chain$2$eigen_subtract
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$dot@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@?$MatrixBase@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@Eigen@@QEBANAEBV01@@Z DD imagerel $LN346
	DD	imagerel $LN346+223
	DD	imagerel $unwind$??$dot@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@?$MatrixBase@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@Eigen@@QEBANAEBV01@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$0$??$dot@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@?$MatrixBase@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@Eigen@@QEBANAEBV01@@Z DD imagerel $LN346+223
	DD	imagerel $LN346+589
	DD	imagerel $chain$0$??$dot@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@?$MatrixBase@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@Eigen@@QEBANAEBV01@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$1$??$dot@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@?$MatrixBase@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@Eigen@@QEBANAEBV01@@Z DD imagerel $LN346+589
	DD	imagerel $LN346+755
	DD	imagerel $chain$1$??$dot@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@?$MatrixBase@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@Eigen@@QEBANAEBV01@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$packet4_subtract DD imagerel $LN32
	DD	imagerel $LN32+341
	DD	imagerel $unwind$packet4_subtract
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$scan_two_pass DD imagerel $LN54
	DD	imagerel $LN54+251
	DD	imagerel $unwind$scan_two_pass
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$scan_fused DD imagerel $LN53
	DD	imagerel $LN53+242
	DD	imagerel $unwind$scan_fused
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?run@?$default_inner_product_impl@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@V12@$00@internal@Eigen@@SANAEBV?$MatrixBase@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@3@0@Z DD imagerel $LN344
	DD	imagerel $LN344+223
	DD	imagerel $unwind$?run@?$default_inner_product_impl@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@V12@$00@internal@Eigen@@SANAEBV?$MatrixBase@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@3@0@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$0$?run@?$default_inner_product_impl@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@V12@$00@internal@Eigen@@SANAEBV?$MatrixBase@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@3@0@Z DD imagerel $LN344+223
	DD	imagerel $LN344+589
	DD	imagerel $chain$0$?run@?$default_inner_product_impl@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@V12@$00@internal@Eigen@@SANAEBV?$MatrixBase@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@3@0@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$1$?run@?$default_inner_product_impl@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@V12@$00@internal@Eigen@@SANAEBV?$MatrixBase@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@3@0@Z DD imagerel $LN344+589
	DD	imagerel $LN344+755
	DD	imagerel $chain$1$?run@?$default_inner_product_impl@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@V12@$00@internal@Eigen@@SANAEBV?$MatrixBase@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@3@0@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?run@?$inner_product_impl@U?$inner_product_evaluator@U?$scalar_inner_product_op@NN$00@internal@Eigen@@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@3@V43@@internal@Eigen@@$00@internal@Eigen@@SANAEBU?$inner_product_evaluator@U?$scalar_inner_product_op@NN$00@internal@Eigen@@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@3@V43@@23@@Z DD imagerel $LN314
	DD	imagerel $LN314+358
	DD	imagerel $unwind$?run@?$inner_product_impl@U?$inner_product_evaluator@U?$scalar_inner_product_op@NN$00@internal@Eigen@@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@3@V43@@internal@Eigen@@$00@internal@Eigen@@SANAEBU?$inner_product_evaluator@U?$scalar_inner_product_op@NN$00@internal@Eigen@@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@3@V43@@23@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$1$?run@?$inner_product_impl@U?$inner_product_evaluator@U?$scalar_inner_product_op@NN$00@internal@Eigen@@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@3@V43@@internal@Eigen@@$00@internal@Eigen@@SANAEBU?$inner_product_evaluator@U?$scalar_inner_product_op@NN$00@internal@Eigen@@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@3@V43@@23@@Z DD imagerel $LN314+358
	DD	imagerel $LN314+486
	DD	imagerel $chain$1$?run@?$inner_product_impl@U?$inner_product_evaluator@U?$scalar_inner_product_op@NN$00@internal@Eigen@@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@3@V43@@internal@Eigen@@$00@internal@Eigen@@SANAEBU?$inner_product_evaluator@U?$scalar_inner_product_op@NN$00@internal@Eigen@@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@3@V43@@23@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$2$?run@?$inner_product_impl@U?$inner_product_evaluator@U?$scalar_inner_product_op@NN$00@internal@Eigen@@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@3@V43@@internal@Eigen@@$00@internal@Eigen@@SANAEBU?$inner_product_evaluator@U?$scalar_inner_product_op@NN$00@internal@Eigen@@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@3@V43@@23@@Z DD imagerel $LN314+486
	DD	imagerel $LN314+776
	DD	imagerel $chain$2$?run@?$inner_product_impl@U?$inner_product_evaluator@U?$scalar_inner_product_op@NN$00@internal@Eigen@@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@3@V43@@internal@Eigen@@$00@internal@Eigen@@SANAEBU?$inner_product_evaluator@U?$scalar_inner_product_op@NN$00@internal@Eigen@@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@3@V43@@23@@Z
pdata	ENDS
;	COMDAT __xmm@80000000000000008000000000000000
CONST	SEGMENT
__xmm@80000000000000008000000000000000 DB 00H, 00H, 00H, 00H, 00H, 00H, 00H
	DB	080H, 00H, 00H, 00H, 00H, 00H, 00H, 00H, 080H
CONST	ENDS
;	COMDAT __xmm@7fffffffffffffff7fffffffffffffff
CONST	SEGMENT
__xmm@7fffffffffffffff7fffffffffffffff DB 0ffH, 0ffH, 0ffH, 0ffH, 0ffH, 0ffH
	DB	0ffH, 07fH, 0ffH, 0ffH, 0ffH, 0ffH, 0ffH, 0ffH, 0ffH, 07fH
CONST	ENDS
;	COMDAT __xmm@7fefffffffffffff7fefffffffffffff
CONST	SEGMENT
__xmm@7fefffffffffffff7fefffffffffffff DB 0ffH, 0ffH, 0ffH, 0ffH, 0ffH, 0ffH
	DB	0efH, 07fH, 0ffH, 0ffH, 0ffH, 0ffH, 0ffH, 0ffH, 0efH, 07fH
CONST	ENDS
;	COMDAT __real@bff0000000000000
CONST	SEGMENT
__real@bff0000000000000 DQ 0bff0000000000000r	; -1
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$2$?run@?$inner_product_impl@U?$inner_product_evaluator@U?$scalar_inner_product_op@NN$00@internal@Eigen@@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@3@V43@@internal@Eigen@@$00@internal@Eigen@@SANAEBU?$inner_product_evaluator@U?$scalar_inner_product_op@NN$00@internal@Eigen@@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@3@V43@@23@@Z DD 021H
	DD	imagerel $LN314
	DD	imagerel $LN314+358
	DD	imagerel $unwind$?run@?$inner_product_impl@U?$inner_product_evaluator@U?$scalar_inner_product_op@NN$00@internal@Eigen@@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@3@V43@@internal@Eigen@@$00@internal@Eigen@@SANAEBU?$inner_product_evaluator@U?$scalar_inner_product_op@NN$00@internal@Eigen@@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@3@V43@@23@@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$1$?run@?$inner_product_impl@U?$inner_product_evaluator@U?$scalar_inner_product_op@NN$00@internal@Eigen@@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@3@V43@@internal@Eigen@@$00@internal@Eigen@@SANAEBU?$inner_product_evaluator@U?$scalar_inner_product_op@NN$00@internal@Eigen@@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@3@V43@@23@@Z DD 040e21H
	DD	02740eH
	DD	043405H
	DD	imagerel $LN314
	DD	imagerel $LN314+358
	DD	imagerel $unwind$?run@?$inner_product_impl@U?$inner_product_evaluator@U?$scalar_inner_product_op@NN$00@internal@Eigen@@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@3@V43@@internal@Eigen@@$00@internal@Eigen@@SANAEBU?$inner_product_evaluator@U?$scalar_inner_product_op@NN$00@internal@Eigen@@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@3@V43@@23@@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?run@?$inner_product_impl@U?$inner_product_evaluator@U?$scalar_inner_product_op@NN$00@internal@Eigen@@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@3@V43@@internal@Eigen@@$00@internal@Eigen@@SANAEBU?$inner_product_evaluator@U?$scalar_inner_product_op@NN$00@internal@Eigen@@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@3@V43@@23@@Z DD 010401H
	DD	02204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$1$?run@?$default_inner_product_impl@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@V12@$00@internal@Eigen@@SANAEBV?$MatrixBase@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@3@0@Z DD 021H
	DD	imagerel $LN344
	DD	imagerel $LN344+223
	DD	imagerel $unwind$?run@?$default_inner_product_impl@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@V12@$00@internal@Eigen@@SANAEBV?$MatrixBase@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@3@0@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$0$?run@?$default_inner_product_impl@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@V12@$00@internal@Eigen@@SANAEBV?$MatrixBase@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@3@0@Z DD 020521H
	DD	023405H
	DD	imagerel $LN344
	DD	imagerel $LN344+223
	DD	imagerel $unwind$?run@?$default_inner_product_impl@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@V12@$00@internal@Eigen@@SANAEBV?$MatrixBase@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@3@0@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?run@?$default_inner_product_impl@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@V12@$00@internal@Eigen@@SANAEBV?$MatrixBase@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@3@0@Z DD 010401H
	DD	02204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$scan_fused DD 0c7d01H
	DD	02887dH
	DD	037877H
	DD	04686eH
	DD	0d640fH
	DD	0c340fH
	DD	0700b920fH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$scan_two_pass DD 081401H
	DD	086414H
	DD	075414H
	DD	063414H
	DD	070103214H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$packet4_subtract DD 030b01H
	DD	0680bH
	DD	02204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$1$??$dot@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@?$MatrixBase@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@Eigen@@QEBANAEBV01@@Z DD 021H
	DD	imagerel $LN346
	DD	imagerel $LN346+223
	DD	imagerel $unwind$??$dot@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@?$MatrixBase@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@Eigen@@QEBANAEBV01@@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$0$??$dot@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@?$MatrixBase@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@Eigen@@QEBANAEBV01@@Z DD 020521H
	DD	023405H
	DD	imagerel $LN346
	DD	imagerel $LN346+223
	DD	imagerel $unwind$??$dot@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@?$MatrixBase@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@Eigen@@QEBANAEBV01@@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$dot@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@?$MatrixBase@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@Eigen@@QEBANAEBV01@@Z DD 010401H
	DD	02204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$2$eigen_subtract DD 021H
	DD	imagerel $LN362
	DD	imagerel $LN362+355
	DD	imagerel $unwind$eigen_subtract
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$1$eigen_subtract DD 040e21H
	DD	04740eH
	DD	063405H
	DD	imagerel $LN362
	DD	imagerel $LN362+355
	DD	imagerel $unwind$eigen_subtract
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$eigen_subtract DD 030901H
	DD	016809H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$packet_subtract DD 020501H
	DD	013405H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?contiguous_dot@detail@linalg@kibo@@YANPEBN0_KN@Z DD 020501H
	DD	013405H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?finite_max_abs@detail@linalg@kibo@@YA_NPEBN_KAEAN@Z DD 0e8d01H
	DD	02888dH
	DD	037887H
	DD	04687eH
	DD	0e6414H
	DD	0d5414H
	DD	0c3414H
	DD	070109214H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?fpclassify@@YAHN@Z DD 010401H
	DD	04204H
xdata	ENDS
; Function compile flags: /Ogtpy
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\assembly-gap\kernels.cpp
; File C:\Users\owner\Documents\git\kibo-linalg\include\kibo\detail\row_kernels.hpp
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\assembly-gap\kernels.cpp
; File C:\Users\owner\Documents\git\kibo-linalg\include\kibo\detail\row_kernels.hpp
; File C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\ucrt\corecrt_math.h
; File C:\Users\owner\Documents\git\kibo-linalg\include\kibo\detail\row_kernels.hpp
; File C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.44.35207\include\cstdlib
; File C:\Users\owner\Documents\git\kibo-linalg\include\kibo\detail\row_kernels.hpp
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\assembly-gap\kernels.cpp
;	COMDAT scan_fused
_TEXT	SEGMENT
a$ = 96
__formal$ = 104
n$ = 112
__formal$ = 120
scan_fused PROC						; COMDAT

; 31   : extern "C" __declspec(noinline) double scan_fused(const double* a,const double*,std::size_t n,double) {

$LN53:
	mov	QWORD PTR [rsp+8], rbx
	mov	QWORD PTR [rsp+16], rsi
	push	rdi
	sub	rsp, 80					; 00000050H
; File C:\Users\owner\Documents\git\kibo-linalg\include\kibo\detail\row_kernels.hpp

; 20   :     const auto sign=_mm_set1_pd(-0.0);

	movdqa	xmm4, XMMWORD PTR __xmm@80000000000000008000000000000000
	xor	ebx, ebx

; 21   :     const auto limit=_mm_set1_pd(std::numeric_limits<double>::max());

	movdqa	xmm5, XMMWORD PTR __xmm@7fefffffffffffff7fefffffffffffff
	xorps	xmm3, xmm3
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\assembly-gap\kernels.cpp

; 31   : extern "C" __declspec(noinline) double scan_fused(const double* a,const double*,std::size_t n,double) {

	mov	rdi, r8
	mov	rsi, rcx
	xorps	xmm2, xmm2
; File C:\Users\owner\Documents\git\kibo-linalg\include\kibo\detail\row_kernels.hpp

; 23   :     auto valid=_mm_cmpeq_pd(_mm_setzero_pd(),_mm_setzero_pd());

	cmpeqpd	xmm3, xmm3

; 24   :     for (;count-i>=2;i+=2) {

	cmp	r8, 2
	jb	SHORT $LN7@scan_fused
	npad	8
$LL8@scan_fused:

; 25   :         const auto absolute=_mm_andnot_pd(sign,_mm_loadu_pd(values+i));

	movups	xmm0, XMMWORD PTR [rcx+rbx*8]
	add	rbx, 2
	mov	rax, rdi
	movaps	xmm1, xmm4
	sub	rax, rbx
	andnps	xmm1, xmm0

; 26   :         valid=_mm_and_pd(valid,_mm_cmple_pd(absolute,limit));

	movaps	xmm0, xmm1
	cmplepd	xmm0, xmm5
	andps	xmm3, xmm0

; 27   :         largest=_mm_max_pd(largest,absolute);

	maxpd	xmm2, xmm1
	cmp	rax, 2
	jae	SHORT $LL8@scan_fused
$LN7@scan_fused:
	movaps	XMMWORD PTR [rsp+64], xmm6

; 28   :     }
; 29   :     if (_mm_movemask_pd(valid)!=3) return false;

	movmskpd eax, xmm3
	movaps	XMMWORD PTR [rsp+48], xmm7
	movaps	XMMWORD PTR [rsp+32], xmm8
	cmp	eax, 3
	jne	SHORT $LN3@scan_fused

; 30   :     maximum=std::max(_mm_cvtsd_f64(largest),_mm_cvtsd_f64(_mm_unpackhi_pd(largest,largest)));

	movaps	xmm7, xmm2
	unpckhpd xmm7, xmm2
	maxsd	xmm7, xmm2

; 32   :     for (;i<count;++i) {

	cmp	rbx, rdi
	jae	SHORT $LN10@scan_fused
	movdqa	xmm8, XMMWORD PTR __xmm@7fffffffffffffff7fffffffffffffff
	npad	5
$LL11@scan_fused:
; File C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\ucrt\corecrt_math.h

; 326  :         return _dtest(&_X);

	movsd	xmm6, QWORD PTR [rsi+rbx*8]
	movaps	xmm0, xmm6
	call	_dclass
; File C:\Users\owner\Documents\git\kibo-linalg\include\kibo\detail\row_kernels.hpp

; 33   :         if (!std::isfinite(values[i])) return false;

	test	ax, ax
	jg	SHORT $LN3@scan_fused
; File C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.44.35207\include\cstdlib

; 24   :     return _CSTD fabs(_Xx);

	andps	xmm6, xmm8
; File C:\Users\owner\Documents\git\kibo-linalg\include\kibo\detail\row_kernels.hpp

; 32   :     for (;i<count;++i) {

	inc	rbx

; 34   :         maximum=std::max(maximum,std::abs(values[i]));

	maxsd	xmm6, xmm7
	movaps	xmm7, xmm6
	cmp	rbx, rdi
	jb	SHORT $LL11@scan_fused
$LN10@scan_fused:
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\assembly-gap\kernels.cpp

; 32   :     double scale=0;return kibo::linalg::detail::finite_max_abs(a,n,scale)?scale:-1;

	movaps	xmm0, xmm7
	jmp	SHORT $LN4@scan_fused
$LN3@scan_fused:
	movsd	xmm0, QWORD PTR __real@bff0000000000000
$LN4@scan_fused:
	movaps	xmm8, XMMWORD PTR [rsp+32]

; 33   : }

	movaps	xmm7, XMMWORD PTR [rsp+48]
	movaps	xmm6, XMMWORD PTR [rsp+64]
	mov	rbx, QWORD PTR [rsp+96]
	mov	rsi, QWORD PTR [rsp+104]
	add	rsp, 80					; 00000050H
	pop	rdi
	ret	0
scan_fused ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\assembly-gap\kernels.cpp
; File C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\ucrt\corecrt_math.h
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\assembly-gap\kernels.cpp
; File C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.44.35207\include\cstdlib
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\assembly-gap\kernels.cpp
; File C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.44.35207\include\cstdlib
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\assembly-gap\kernels.cpp
; File C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.44.35207\include\cstdlib
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\assembly-gap\kernels.cpp
; File C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.44.35207\include\cstdlib
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\assembly-gap\kernels.cpp
; File C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.44.35207\include\cstdlib
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\assembly-gap\kernels.cpp
;	COMDAT scan_two_pass
_TEXT	SEGMENT
a$ = 48
__formal$ = 56
n$ = 64
__formal$ = 72
scan_two_pass PROC					; COMDAT

; 27   : extern "C" __declspec(noinline) double scan_two_pass(const double* a,const double*,std::size_t n,double) {

$LN54:
	mov	QWORD PTR [rsp+8], rbx
	mov	QWORD PTR [rsp+16], rbp
	mov	QWORD PTR [rsp+24], rsi
	push	rdi
	sub	rsp, 32					; 00000020H

; 28   :     for(std::size_t i=0;i<n;++i)if(!std::isfinite(a[i]))return -1;

	xor	edi, edi
	mov	rsi, r8
	mov	rbp, rcx
	mov	ebx, edi
	test	r8, r8
	je	SHORT $LN3@scan_two_p
$LL4@scan_two_p:
; File C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\ucrt\corecrt_math.h

; 326  :         return _dtest(&_X);

	movsd	xmm0, QWORD PTR [rbp+rbx*8]
	call	_dclass
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\assembly-gap\kernels.cpp

; 28   :     for(std::size_t i=0;i<n;++i)if(!std::isfinite(a[i]))return -1;

	test	ax, ax
	jg	$LN25@scan_two_p
	inc	rbx
	cmp	rbx, rsi
	jb	SHORT $LL4@scan_two_p
$LN3@scan_two_p:

; 29   :     double scale=0;for(std::size_t i=0;i<n;++i)if(std::abs(a[i])>scale)scale=std::abs(a[i]);return scale;

	movdqa	xmm2, XMMWORD PTR __xmm@7fffffffffffffff7fffffffffffffff
	xorps	xmm0, xmm0
	cmp	rsi, 4
	jb	SHORT $LC33@scan_two_p
	lea	rcx, QWORD PTR [rsi-4]
	shr	rcx, 2
	lea	rax, QWORD PTR [rbp+16]
	inc	rcx
	lea	rdi, QWORD PTR [rcx*4]
	npad	9
$LL38@scan_two_p:
; File C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.44.35207\include\cstdlib

; 24   :     return _CSTD fabs(_Xx);

	movsd	xmm1, QWORD PTR [rax-16]
	andps	xmm1, xmm2
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\assembly-gap\kernels.cpp

; 29   :     double scale=0;for(std::size_t i=0;i<n;++i)if(std::abs(a[i])>scale)scale=std::abs(a[i]);return scale;

	comisd	xmm1, xmm0
	jbe	SHORT $LN34@scan_two_p
	movaps	xmm0, xmm1
$LN34@scan_two_p:
; File C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.44.35207\include\cstdlib

; 24   :     return _CSTD fabs(_Xx);

	movsd	xmm1, QWORD PTR [rax-8]
	andps	xmm1, xmm2
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\assembly-gap\kernels.cpp

; 29   :     double scale=0;for(std::size_t i=0;i<n;++i)if(std::abs(a[i])>scale)scale=std::abs(a[i]);return scale;

	comisd	xmm1, xmm0
	jbe	SHORT $LN35@scan_two_p
	movaps	xmm0, xmm1
$LN35@scan_two_p:
; File C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.44.35207\include\cstdlib

; 24   :     return _CSTD fabs(_Xx);

	movsd	xmm1, QWORD PTR [rax]
	andps	xmm1, xmm2
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\assembly-gap\kernels.cpp

; 29   :     double scale=0;for(std::size_t i=0;i<n;++i)if(std::abs(a[i])>scale)scale=std::abs(a[i]);return scale;

	comisd	xmm1, xmm0
	jbe	SHORT $LN36@scan_two_p
	movaps	xmm0, xmm1
$LN36@scan_two_p:
; File C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.44.35207\include\cstdlib

; 24   :     return _CSTD fabs(_Xx);

	movsd	xmm1, QWORD PTR [rax+8]
	andps	xmm1, xmm2
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\assembly-gap\kernels.cpp

; 29   :     double scale=0;for(std::size_t i=0;i<n;++i)if(std::abs(a[i])>scale)scale=std::abs(a[i]);return scale;

	comisd	xmm1, xmm0
	jbe	SHORT $LN37@scan_two_p
	movaps	xmm0, xmm1
$LN37@scan_two_p:
	add	rax, 32					; 00000020H
	sub	rcx, 1
	jne	SHORT $LL38@scan_two_p
$LC33@scan_two_p:
	cmp	rdi, rsi
	jae	SHORT $LN32@scan_two_p
$LC7@scan_two_p:
; File C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.44.35207\include\cstdlib

; 24   :     return _CSTD fabs(_Xx);

	movsd	xmm1, QWORD PTR [rbp+rdi*8]
	andps	xmm1, xmm2
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\assembly-gap\kernels.cpp

; 29   :     double scale=0;for(std::size_t i=0;i<n;++i)if(std::abs(a[i])>scale)scale=std::abs(a[i]);return scale;

	comisd	xmm1, xmm0
	jbe	SHORT $LN5@scan_two_p
	movaps	xmm0, xmm1
$LN5@scan_two_p:
	inc	rdi
	cmp	rdi, rsi
	jb	SHORT $LC7@scan_two_p
$LN32@scan_two_p:

; 30   : }

	mov	rbx, QWORD PTR [rsp+48]
	mov	rbp, QWORD PTR [rsp+56]
	mov	rsi, QWORD PTR [rsp+64]
	add	rsp, 32					; 00000020H
	pop	rdi
	ret	0
$LN25@scan_two_p:

; 28   :     for(std::size_t i=0;i<n;++i)if(!std::isfinite(a[i]))return -1;

	movsd	xmm0, QWORD PTR __real@bff0000000000000
	jmp	SHORT $LN32@scan_two_p
scan_two_pass ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\assembly-gap\kernels.cpp
;	COMDAT packet4_subtract
_TEXT	SEGMENT
a$ = 32
b$ = 40
n$ = 48
value$ = 56
packet4_subtract PROC					; COMDAT

; 15   : extern "C" __declspec(noinline) double packet4_subtract(const double* a,const double* b,std::size_t n,double value) {

$LN32:
	sub	rsp, 24

; 16   :     auto s0=_mm_setzero_pd(),s1=s0,s2=s0,s3=s0;std::size_t i=0;

	mov	r9, rcx
	movaps	XMMWORD PTR [rsp], xmm6
	sub	r9, rdx
	xor	r10d, r10d
	mov	r11, rcx
	xorps	xmm4, xmm4
	xorps	xmm5, xmm5
	xorps	xmm6, xmm6
	xorps	xmm2, xmm2

; 17   :     for(;n-i>=8;i+=8){

	cmp	r8, 8
	jb	SHORT $LN25@packet4_su

; 16   :     auto s0=_mm_setzero_pd(),s1=s0,s2=s0,s3=s0;std::size_t i=0;

	lea	rcx, QWORD PTR [rdx+16]
	npad	6
$LL4@packet4_su:

; 18   :         s0=_mm_add_pd(s0,_mm_mul_pd(_mm_loadu_pd(a+i),_mm_loadu_pd(b+i)));

	movups	xmm0, XMMWORD PTR [rcx-16]
	add	r10, 8
	mov	rax, r8
	movups	xmm1, XMMWORD PTR [r9+rcx-16]
	sub	rax, r10
	mulpd	xmm1, xmm0

; 19   :         s1=_mm_add_pd(s1,_mm_mul_pd(_mm_loadu_pd(a+i+2),_mm_loadu_pd(b+i+2)));

	movups	xmm0, XMMWORD PTR [rcx]
	addpd	xmm4, xmm1
	movups	xmm1, XMMWORD PTR [rcx+r9]
	mulpd	xmm1, xmm0

; 20   :         s2=_mm_add_pd(s2,_mm_mul_pd(_mm_loadu_pd(a+i+4),_mm_loadu_pd(b+i+4)));

	movups	xmm0, XMMWORD PTR [rcx+16]
	addpd	xmm5, xmm1
	movups	xmm1, XMMWORD PTR [r9+rcx+16]
	mulpd	xmm1, xmm0

; 21   :         s3=_mm_add_pd(s3,_mm_mul_pd(_mm_loadu_pd(a+i+6),_mm_loadu_pd(b+i+6)));

	movups	xmm0, XMMWORD PTR [rcx+32]
	addpd	xmm6, xmm1
	movups	xmm1, XMMWORD PTR [r9+rcx+32]
	add	rcx, 64					; 00000040H
	mulpd	xmm1, xmm0
	addpd	xmm2, xmm1
	cmp	rax, 8
	jae	SHORT $LL4@packet4_su
$LN25@packet4_su:

; 22   :     }
; 23   :     auto total=_mm_add_pd(_mm_add_pd(s0,s1),_mm_add_pd(s2,s3));

	addpd	xmm2, xmm6
	addpd	xmm5, xmm4
	addpd	xmm2, xmm5

; 24   :     double dot=_mm_cvtsd_f64(total)+_mm_cvtsd_f64(_mm_unpackhi_pd(total,total));

	movaps	xmm1, xmm2
	unpckhpd xmm1, xmm2
	addsd	xmm1, xmm2

; 25   :     for(;i<n;++i)dot+=a[i]*b[i];return value-dot;

	cmp	r10, r8
	jae	$LN19@packet4_su
	mov	rax, r8
	sub	rax, r10
	cmp	rax, 4
	jb	SHORT $LC20@packet4_su
	mov	rcx, r8
	lea	rax, QWORD PTR [rdx+8]
	sub	rcx, r10
	lea	rax, QWORD PTR [rax+r10*8]
	sub	rcx, 4
	shr	rcx, 2
	inc	rcx
	lea	r10, QWORD PTR [r10+rcx*4]
$LL21@packet4_su:
	movsd	xmm2, QWORD PTR [rax+r9-8]
	mulsd	xmm2, QWORD PTR [rax-8]
	movsd	xmm0, QWORD PTR [rax+r9]
	mulsd	xmm0, QWORD PTR [rax]
	addsd	xmm2, xmm1
	movsd	xmm1, QWORD PTR [rax+r9+8]
	mulsd	xmm1, QWORD PTR [rax+8]
	addsd	xmm2, xmm0
	addsd	xmm2, xmm1
	movsd	xmm1, QWORD PTR [rax+r9+16]
	mulsd	xmm1, QWORD PTR [rax+16]
	add	rax, 32					; 00000020H
	addsd	xmm1, xmm2
	sub	rcx, 1
	jne	SHORT $LL21@packet4_su
	mov	r9, r11
	sub	r9, rdx
$LC20@packet4_su:
	cmp	r10, r8
	jae	SHORT $LN19@packet4_su
	lea	rax, QWORD PTR [rdx+r10*8]
	sub	r8, r10
$LC15@packet4_su:
	movsd	xmm0, QWORD PTR [r9+rax]
	mulsd	xmm0, QWORD PTR [rax]
	add	rax, 8
	addsd	xmm1, xmm0
	sub	r8, 1
	jne	SHORT $LC15@packet4_su
$LN19@packet4_su:

; 26   : }

	movaps	xmm6, XMMWORD PTR [rsp]
	subsd	xmm3, xmm1
	movaps	xmm0, xmm3
	add	rsp, 24
	ret	0
packet4_subtract ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\Dot.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\CoreEvaluators.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\Dot.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\GenericPacketMath.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\CoreEvaluators.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\MathFunctions.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\MathFunctions.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\MathFunctions.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\Dot.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\MathFunctions.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\MathFunctions.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\Reductions.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\CoreEvaluators.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\MathFunctions.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\MathFunctions.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\MathFunctions.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\Dot.h
;	COMDAT ??$dot@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@?$MatrixBase@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@Eigen@@QEBANAEBV01@@Z
_TEXT	SEGMENT
presult1$2 = 0
presult2$3 = 0
this$ = 32
other$ = 40
??$dot@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@?$MatrixBase@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@Eigen@@QEBANAEBV01@@Z PROC ; Eigen::MatrixBase<Eigen::Map<Eigen::Matrix<double,-1,1,0,-1,1> const ,0,Eigen::Stride<0,0> > >::dot<Eigen::Map<Eigen::Matrix<double,-1,1,0,-1,1> const ,0,Eigen::Stride<0,0> > >, COMDAT

; 52   :     MatrixBase<Derived>::dot(const MatrixBase<OtherDerived>& other) const {

$LN346:
	sub	rsp, 24
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\CoreEvaluators.h

; 1244 :         m_outerStride(map.outerStride()) {

	mov	r10, QWORD PTR [rcx+8]
	mov	r9, QWORD PTR [rcx]

; 1242 :       : m_data(const_cast<PointerType>(map.data())),

	mov	r8, QWORD PTR [rdx]
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h

; 138  :     if (size < PacketSize) return inner_product_impl<Evaluator, false>::run(eval);

	cmp	r10, 2
	jae	$LN31@dot

; 118  :     if (size == 0) return Scalar(0);

	test	r10, r10
	jne	SHORT $LN193@dot
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\Dot.h

; 53   :   return internal::dot_impl<Derived, OtherDerived>::run(derived(), other.derived());

	xorps	xmm2, xmm2
	movaps	xmm0, xmm2

; 54   : }

	add	rsp, 24
	ret	0
$LN193@dot:
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\GenericPacketMath.h

; 365  :   return a * b;

	movsd	xmm2, QWORD PTR [r8]
	mov	ecx, 1
	mulsd	xmm2, QWORD PTR [r9]
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h

; 121  :     for (Index k = 1; k < size; k++) {

	cmp	r10, rcx
	jle	$LN293@dot
	lea	rax, QWORD PTR [r10-1]
	cmp	rax, 4
	jl	SHORT $LC294@dot
	lea	rdx, QWORD PTR [r10-3]
	mov	eax, 8
	npad	13
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\CoreEvaluators.h

; 1256 :     return m_data[index * m_innerStride.value()];

$LL295@dot:
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\MathFunctions.h

; 1003 :     return x * y + z;

	movsd	xmm1, QWORD PTR [r9+rcx*8+8]
	mulsd	xmm1, QWORD PTR [r8+rcx*8+8]
	movsd	xmm0, QWORD PTR [r9+rcx*8]
	mulsd	xmm0, QWORD PTR [r8+rcx*8]
	addsd	xmm0, xmm2
	movaps	xmm2, xmm1
	movsd	xmm1, QWORD PTR [r9+rcx*8+24]
	mulsd	xmm1, QWORD PTR [r8+rcx*8+24]
	addsd	xmm2, xmm0
	movsd	xmm0, QWORD PTR [r8+rax+16]
	mulsd	xmm0, QWORD PTR [r9+rcx*8+16]
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h

; 122  :       result = eval.coeff(result, k);

	add	rax, 32					; 00000020H
	add	rcx, 4
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\MathFunctions.h

; 1003 :     return x * y + z;

	addsd	xmm2, xmm0
	addsd	xmm2, xmm1
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h

; 122  :       result = eval.coeff(result, k);

	cmp	rcx, rdx
	jl	SHORT $LL295@dot

; 121  :     for (Index k = 1; k < size; k++) {

	cmp	rcx, r10
	jge	SHORT $LN293@dot
$LC294@dot:
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\MathFunctions.h

; 1003 :     return x * y + z;

	movsd	xmm1, QWORD PTR [r9+rcx*8]
	mulsd	xmm1, QWORD PTR [r8+rcx*8]
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h

; 121  :     for (Index k = 1; k < size; k++) {

	inc	rcx

; 122  :       result = eval.coeff(result, k);

	addsd	xmm2, xmm1
	cmp	rcx, r10
	jl	SHORT $LC294@dot
$LN293@dot:
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\Dot.h

; 53   :   return internal::dot_impl<Derived, OtherDerived>::run(derived(), other.derived());

	movaps	xmm0, xmm2

; 54   : }

	add	rsp, 24
	ret	0
$LN31@dot:
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h

; 627  :   return _mm_mul_pd(a, b);

	movups	xmm2, XMMWORD PTR [r8]
	mov	QWORD PTR [rsp+16], rbx
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\MathFunctions.h

; 1357 :   return ub * (ua / ub);

	mov	r11, r10
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h

; 627  :   return _mm_mul_pd(a, b);

	movups	xmm0, XMMWORD PTR [r9]
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\MathFunctions.h

; 1357 :   return ub * (ua / ub);

	and	r11, -2
	mov	rax, r10
	and	rax, -8
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h

; 143  :     const UnsignedIndex numRemPackets = (packetEnd - quadEnd) / PacketSize;

	mov	rbx, r11
	sub	rbx, rax
	mov	rcx, r10
	shr	rbx, 1
	shr	rcx, 1
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h

; 627  :   return _mm_mul_pd(a, b);

	mulpd	xmm2, xmm0
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h

; 148  :     if (numPackets >= 2) presult1 = eval.template packet<Packet>(1 * PacketSize);

	cmp	rcx, 2
	jb	SHORT $LN323@dot
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h

; 627  :   return _mm_mul_pd(a, b);

	movups	xmm3, XMMWORD PTR [r9+16]
	movups	xmm0, XMMWORD PTR [r8+16]
	mulpd	xmm3, xmm0
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h

; 148  :     if (numPackets >= 2) presult1 = eval.template packet<Packet>(1 * PacketSize);

	jmp	SHORT $LN32@dot
$LN323@dot:
	movaps	xmm3, XMMWORD PTR presult1$2[rsp]
$LN32@dot:

; 149  :     if (numPackets >= 3) presult2 = eval.template packet<Packet>(2 * PacketSize);

	cmp	rcx, 3
	jb	SHORT $LN324@dot
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h

; 627  :   return _mm_mul_pd(a, b);

	movups	xmm4, XMMWORD PTR [r9+32]
	movups	xmm0, XMMWORD PTR [r8+32]
	mulpd	xmm4, xmm0
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h

; 149  :     if (numPackets >= 3) presult2 = eval.template packet<Packet>(2 * PacketSize);

	jmp	SHORT $LN33@dot
$LN324@dot:
	movaps	xmm4, XMMWORD PTR presult2$3[rsp]
$LN33@dot:

; 150  :     if (numPackets >= 4) {

	cmp	rcx, 4
	jb	$LN34@dot
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h

; 627  :   return _mm_mul_pd(a, b);

	movups	xmm5, XMMWORD PTR [r9+48]
	movups	xmm0, XMMWORD PTR [r8+48]
	mulpd	xmm5, xmm0
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h

; 153  :       for (UnsignedIndex k = 4 * PacketSize; k < quadEnd; k += 4 * PacketSize) {

	cmp	rax, 8
	jbe	SHORT $LN26@dot
	lea	rcx, QWORD PTR [rax-9]
	mov	edx, 96					; 00000060H
	shr	rcx, 3
	inc	rcx
	npad	5
$LL27@dot:
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h

; 627  :   return _mm_mul_pd(a, b);

	movups	xmm0, XMMWORD PTR [rdx+r9-32]
	movups	xmm1, XMMWORD PTR [r8+rdx-32]
	mulpd	xmm1, xmm0
	movups	xmm0, XMMWORD PTR [rdx+r9-16]

; 504  :   return _mm_add_pd(a, b);

	addpd	xmm2, xmm1

; 627  :   return _mm_mul_pd(a, b);

	movups	xmm1, XMMWORD PTR [r8+rdx-16]
	mulpd	xmm1, xmm0
	movups	xmm0, XMMWORD PTR [rdx+r9]

; 504  :   return _mm_add_pd(a, b);

	addpd	xmm3, xmm1

; 627  :   return _mm_mul_pd(a, b);

	movups	xmm1, XMMWORD PTR [r8+rdx]
	mulpd	xmm1, xmm0
	movups	xmm0, XMMWORD PTR [rdx+r9+16]

; 504  :   return _mm_add_pd(a, b);

	addpd	xmm4, xmm1

; 627  :   return _mm_mul_pd(a, b);

	movups	xmm1, XMMWORD PTR [r8+rdx+16]
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h

; 153  :       for (UnsignedIndex k = 4 * PacketSize; k < quadEnd; k += 4 * PacketSize) {

	add	rdx, 64					; 00000040H
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h

; 627  :   return _mm_mul_pd(a, b);

	mulpd	xmm1, xmm0

; 504  :   return _mm_add_pd(a, b);

	addpd	xmm5, xmm1
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h

; 153  :       for (UnsignedIndex k = 4 * PacketSize; k < quadEnd; k += 4 * PacketSize) {

	sub	rcx, 1
	jne	SHORT $LL27@dot
$LN26@dot:

; 154  :         presult0 = eval.packet(presult0, k + 0 * PacketSize);
; 155  :         presult1 = eval.packet(presult1, k + 1 * PacketSize);
; 156  :         presult2 = eval.packet(presult2, k + 2 * PacketSize);
; 157  :         presult3 = eval.packet(presult3, k + 3 * PacketSize);
; 158  :       }
; 159  : 
; 160  :       if (numRemPackets >= 1) presult0 = eval.packet(presult0, quadEnd + 0 * PacketSize);

	cmp	rbx, 1
	jb	SHORT $LN35@dot
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h

; 627  :   return _mm_mul_pd(a, b);

	movups	xmm1, XMMWORD PTR [r8+rax*8]
	movups	xmm0, XMMWORD PTR [r9+rax*8]
	mulpd	xmm1, xmm0

; 504  :   return _mm_add_pd(a, b);

	addpd	xmm2, xmm1
$LN35@dot:
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h

; 161  :       if (numRemPackets >= 2) presult1 = eval.packet(presult1, quadEnd + 1 * PacketSize);

	cmp	rbx, 2
	jb	SHORT $LN36@dot
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h

; 627  :   return _mm_mul_pd(a, b);

	movups	xmm1, XMMWORD PTR [r8+rax*8+16]
	movups	xmm0, XMMWORD PTR [r9+rax*8+16]
	mulpd	xmm1, xmm0

; 504  :   return _mm_add_pd(a, b);

	addpd	xmm3, xmm1
$LN36@dot:
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h

; 162  :       if (numRemPackets == 3) presult2 = eval.packet(presult2, quadEnd + 2 * PacketSize);

	cmp	rbx, 3
	jne	SHORT $LN37@dot
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h

; 627  :   return _mm_mul_pd(a, b);

	movups	xmm1, XMMWORD PTR [r8+rax*8+32]
	movups	xmm0, XMMWORD PTR [r9+rax*8+32]
	mulpd	xmm1, xmm0

; 504  :   return _mm_add_pd(a, b);

	addpd	xmm4, xmm1
$LN37@dot:
	addpd	xmm4, xmm5
	addpd	xmm3, xmm4
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h

; 171  :     for (UnsignedIndex k = packetEnd; k < size; k++) {

	jmp	SHORT $LN321@dot
$LN34@dot:

; 163  : 
; 164  :       presult2 = padd(presult2, presult3);
; 165  :     }
; 166  : 
; 167  :     if (numPackets >= 3) presult1 = padd(presult1, presult2);

	cmp	rcx, 3
	jb	SHORT $LN38@dot
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h

; 504  :   return _mm_add_pd(a, b);

	addpd	xmm3, xmm4
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h

; 171  :     for (UnsignedIndex k = packetEnd; k < size; k++) {

	jmp	SHORT $LN321@dot
$LN38@dot:

; 168  :     if (numPackets >= 2) presult0 = padd(presult0, presult1);

	cmp	rcx, 2
	jb	SHORT $LN39@dot
$LN321@dot:
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h

; 504  :   return _mm_add_pd(a, b);

	addpd	xmm2, xmm3
$LN39@dot:
	mov	rbx, QWORD PTR [rsp+16]
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\Reductions.h

; 270  :     tmp = Op::packetOp(a, _mm_unpackhi_pd(a, a));

	movaps	xmm0, xmm2
	unpckhpd xmm0, xmm2
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h

; 504  :   return _mm_add_pd(a, b);

	addpd	xmm0, xmm2
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h

; 171  :     for (UnsignedIndex k = packetEnd; k < size; k++) {

	cmp	r11, r10
	jae	$LN296@dot
	mov	rax, r10
	sub	rax, r11
	cmp	rax, 4
	jb	SHORT $LN320@dot
	mov	rdx, r10
	lea	rax, QWORD PTR [r9+8]
	sub	rdx, r11
	lea	rax, QWORD PTR [rax+r11*8]
	sub	rdx, 4
	mov	rcx, r8
	shr	rdx, 2
	sub	rcx, r9
	inc	rdx
	lea	r11, QWORD PTR [r11+rdx*4]
	npad	4
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\CoreEvaluators.h

; 1256 :     return m_data[index * m_innerStride.value()];

$LL298@dot:
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\MathFunctions.h

; 1003 :     return x * y + z;

	movsd	xmm2, QWORD PTR [rcx+rax-8]
	mulsd	xmm2, QWORD PTR [rax-8]
	movsd	xmm1, QWORD PTR [rcx+rax+8]
	mulsd	xmm1, QWORD PTR [rax+8]
	addsd	xmm2, xmm0
	movsd	xmm0, QWORD PTR [rcx+rax]
	mulsd	xmm0, QWORD PTR [rax]
	addsd	xmm2, xmm0
	movsd	xmm0, QWORD PTR [rcx+rax+16]
	mulsd	xmm0, QWORD PTR [rax+16]
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h

; 172  :       result = eval.coeff(result, k);

	add	rax, 32					; 00000020H
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\MathFunctions.h

; 1003 :     return x * y + z;

	addsd	xmm2, xmm1
	addsd	xmm2, xmm0
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h

; 172  :       result = eval.coeff(result, k);

	movaps	xmm0, xmm2
	sub	rdx, 1
	jne	SHORT $LL298@dot

; 171  :     for (UnsignedIndex k = packetEnd; k < size; k++) {

	cmp	r11, r10
	jae	SHORT $LN296@dot
$LN320@dot:
	sub	r8, r9
	lea	rax, QWORD PTR [r9+r11*8]
	sub	r10, r11
$LC311@dot:
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\MathFunctions.h

; 1003 :     return x * y + z;

	movsd	xmm1, QWORD PTR [rax+r8]
	mulsd	xmm1, QWORD PTR [rax]
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h

; 171  :     for (UnsignedIndex k = packetEnd; k < size; k++) {

	add	rax, 8

; 172  :       result = eval.coeff(result, k);

	addsd	xmm0, xmm1
	sub	r10, 1
	jne	SHORT $LC311@dot
$LN296@dot:
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\Dot.h

; 54   : }

	add	rsp, 24
	ret	0
??$dot@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@?$MatrixBase@V?$Map@$$CBV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@@Eigen@@QEBANAEBV01@@Z ENDP ; Eigen::MatrixBase<Eigen::Map<Eigen::Matrix<double,-1,1,0,-1,1> const ,0,Eigen::Stride<0,0> > >::dot<Eigen::Map<Eigen::Matrix<double,-1,1,0,-1,1> const ,0,Eigen::Stride<0,0> > >
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\assembly-gap\kernels.cpp
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\assembly-gap\kernels.cpp
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\GenericPacketMath.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\CoreEvaluators.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\MathFunctions.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\MathFunctions.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\MathFunctions.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\assembly-gap\kernels.cpp
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\MathFunctions.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\MathFunctions.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\Reductions.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\CoreEvaluators.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\MathFunctions.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\MathFunctions.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\MathFunctions.h
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\assembly-gap\kernels.cpp
;	COMDAT eigen_subtract
_TEXT	SEGMENT
presult1$2 = 0
presult2$3 = 0
a$ = 48
b$ = 56
n$ = 64
value$ = 72
eigen_subtract PROC					; COMDAT

; 11   : extern "C" __declspec(noinline) double eigen_subtract(const double* a,const double* b,std::size_t n,double value) {

$LN362:
	sub	rsp, 40					; 00000028H
	movaps	XMMWORD PTR [rsp+16], xmm6
	movaps	xmm6, xmm3
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h

; 138  :     if (size < PacketSize) return inner_product_impl<Evaluator, false>::run(eval);

	cmp	r8, 2
	jae	$LN55@eigen_subt

; 118  :     if (size == 0) return Scalar(0);

	test	r8, r8
	jne	SHORT $LN217@eigen_subt
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\assembly-gap\kernels.cpp

; 12   :     return value-Eigen::Map<const Eigen::VectorXd,Eigen::Unaligned>(a,n).dot(Eigen::Map<const Eigen::VectorXd,Eigen::Unaligned>(b,n));

	xorps	xmm4, xmm4
	subsd	xmm6, xmm4
	movaps	xmm0, xmm6

; 13   : }

	movaps	xmm6, XMMWORD PTR [rsp+16]
	add	rsp, 40					; 00000028H
	ret	0
$LN217@eigen_subt:
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\GenericPacketMath.h

; 365  :   return a * b;

	movsd	xmm4, QWORD PTR [rcx]
	mov	r10d, 1
	mulsd	xmm4, QWORD PTR [rdx]
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h

; 121  :     for (Index k = 1; k < size; k++) {

	cmp	r8, r10
	jle	$LN320@eigen_subt
	lea	rax, QWORD PTR [r8-1]
	sub	rdx, rcx
	cmp	rax, 4
	jl	SHORT $LC318@eigen_subt
	lea	r9, QWORD PTR [r8-5]
	shr	r9, 2
	lea	rax, QWORD PTR [rcx+16]
	inc	r9
	lea	r10, QWORD PTR [r9*4+1]
	npad	6
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\CoreEvaluators.h

; 1256 :     return m_data[index * m_innerStride.value()];

$LL319@eigen_subt:
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\MathFunctions.h

; 1003 :     return x * y + z;

	movsd	xmm1, QWORD PTR [rdx+rax-8]
	mulsd	xmm1, QWORD PTR [rax-8]
	movsd	xmm0, QWORD PTR [rdx+rax]
	mulsd	xmm0, QWORD PTR [rax]
	addsd	xmm4, xmm1
	movsd	xmm1, QWORD PTR [rdx+rax+8]
	mulsd	xmm1, QWORD PTR [rax+8]
	addsd	xmm4, xmm0
	movsd	xmm0, QWORD PTR [rdx+rax+16]
	mulsd	xmm0, QWORD PTR [rax+16]
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h

; 122  :       result = eval.coeff(result, k);

	add	rax, 32					; 00000020H
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\MathFunctions.h

; 1003 :     return x * y + z;

	addsd	xmm4, xmm1
	addsd	xmm4, xmm0
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h

; 122  :       result = eval.coeff(result, k);

	sub	r9, 1
	jne	SHORT $LL319@eigen_subt

; 121  :     for (Index k = 1; k < size; k++) {

	cmp	r10, r8
	jge	$LN320@eigen_subt
$LC318@eigen_subt:
	lea	rax, QWORD PTR [rcx+r10*8]
	sub	r8, r10
$LC332@eigen_subt:
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\MathFunctions.h

; 1003 :     return x * y + z;

	movsd	xmm0, QWORD PTR [rax+rdx]
	mulsd	xmm0, QWORD PTR [rax]
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h

; 121  :     for (Index k = 1; k < size; k++) {

	add	rax, 8

; 122  :       result = eval.coeff(result, k);

	addsd	xmm4, xmm0
	sub	r8, 1
	jne	SHORT $LC332@eigen_subt
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\assembly-gap\kernels.cpp

; 12   :     return value-Eigen::Map<const Eigen::VectorXd,Eigen::Unaligned>(a,n).dot(Eigen::Map<const Eigen::VectorXd,Eigen::Unaligned>(b,n));

	subsd	xmm6, xmm4
	movaps	xmm0, xmm6

; 13   : }

	movaps	xmm6, XMMWORD PTR [rsp+16]
	add	rsp, 40					; 00000028H
	ret	0
$LN55@eigen_subt:
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h

; 627  :   return _mm_mul_pd(a, b);

	movups	xmm2, XMMWORD PTR [rcx]
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\MathFunctions.h

; 1357 :   return ub * (ua / ub);

	mov	r11, r8
	mov	rax, r8
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h

; 627  :   return _mm_mul_pd(a, b);

	movups	xmm0, XMMWORD PTR [rdx]
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\MathFunctions.h

; 1357 :   return ub * (ua / ub);

	and	r11, -2
	and	rax, -8
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h

; 143  :     const UnsignedIndex numRemPackets = (packetEnd - quadEnd) / PacketSize;

	mov	r10, r11
	mov	r9, r8
	sub	r10, rax
	shr	r9, 1
	shr	r10, 1
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h

; 627  :   return _mm_mul_pd(a, b);

	mulpd	xmm2, xmm0
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h

; 148  :     if (numPackets >= 2) presult1 = eval.template packet<Packet>(1 * PacketSize);

	cmp	r9, 2
	jb	SHORT $LN343@eigen_subt
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h

; 627  :   return _mm_mul_pd(a, b);

	movups	xmm3, XMMWORD PTR [rcx+16]
	movups	xmm0, XMMWORD PTR [rdx+16]
	mulpd	xmm3, xmm0
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h

; 148  :     if (numPackets >= 2) presult1 = eval.template packet<Packet>(1 * PacketSize);

	jmp	SHORT $LN56@eigen_subt
$LN343@eigen_subt:
	movaps	xmm3, XMMWORD PTR presult1$2[rsp]
$LN56@eigen_subt:

; 149  :     if (numPackets >= 3) presult2 = eval.template packet<Packet>(2 * PacketSize);

	cmp	r9, 3
	jb	SHORT $LN344@eigen_subt
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h

; 627  :   return _mm_mul_pd(a, b);

	movups	xmm4, XMMWORD PTR [rcx+32]
	movups	xmm0, XMMWORD PTR [rdx+32]
	mulpd	xmm4, xmm0
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h

; 149  :     if (numPackets >= 3) presult2 = eval.template packet<Packet>(2 * PacketSize);

	jmp	SHORT $LN57@eigen_subt
$LN344@eigen_subt:
	movaps	xmm4, XMMWORD PTR presult2$3[rsp]
$LN57@eigen_subt:

; 150  :     if (numPackets >= 4) {

	cmp	r9, 4
	jb	$LN58@eigen_subt
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h

; 627  :   return _mm_mul_pd(a, b);

	movups	xmm5, XMMWORD PTR [rcx+48]
	movups	xmm0, XMMWORD PTR [rdx+48]
	mulpd	xmm5, xmm0
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h

; 153  :       for (UnsignedIndex k = 4 * PacketSize; k < quadEnd; k += 4 * PacketSize) {

	cmp	rax, 8
	jbe	$LN50@eigen_subt
	mov	QWORD PTR [rsp+48], rbx
	lea	r9, QWORD PTR [rcx+80]
	mov	QWORD PTR [rsp+32], rdi
	lea	rbx, QWORD PTR [rax-9]
	mov	rdi, rdx
	shr	rbx, 3
	sub	rdi, rcx
	inc	rbx
	npad	14
$LL51@eigen_subt:
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h

; 627  :   return _mm_mul_pd(a, b);

	movups	xmm0, XMMWORD PTR [r9-16]
	movups	xmm1, XMMWORD PTR [rdi+r9-16]
	mulpd	xmm1, xmm0
	movups	xmm0, XMMWORD PTR [r9]

; 504  :   return _mm_add_pd(a, b);

	addpd	xmm2, xmm1

; 627  :   return _mm_mul_pd(a, b);

	movups	xmm1, XMMWORD PTR [r9+rdi]
	mulpd	xmm1, xmm0
	movups	xmm0, XMMWORD PTR [r9+16]

; 504  :   return _mm_add_pd(a, b);

	addpd	xmm3, xmm1

; 627  :   return _mm_mul_pd(a, b);

	movups	xmm1, XMMWORD PTR [r9+rdi+16]
	mulpd	xmm1, xmm0
	movups	xmm0, XMMWORD PTR [r9+32]

; 504  :   return _mm_add_pd(a, b);

	addpd	xmm4, xmm1

; 627  :   return _mm_mul_pd(a, b);

	movups	xmm1, XMMWORD PTR [rdi+r9+32]
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h

; 153  :       for (UnsignedIndex k = 4 * PacketSize; k < quadEnd; k += 4 * PacketSize) {

	add	r9, 64					; 00000040H
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h

; 627  :   return _mm_mul_pd(a, b);

	mulpd	xmm1, xmm0

; 504  :   return _mm_add_pd(a, b);

	addpd	xmm5, xmm1
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h

; 153  :       for (UnsignedIndex k = 4 * PacketSize; k < quadEnd; k += 4 * PacketSize) {

	sub	rbx, 1
	jne	SHORT $LL51@eigen_subt
	mov	rdi, QWORD PTR [rsp+32]
	mov	rbx, QWORD PTR [rsp+48]
$LN50@eigen_subt:

; 154  :         presult0 = eval.packet(presult0, k + 0 * PacketSize);
; 155  :         presult1 = eval.packet(presult1, k + 1 * PacketSize);
; 156  :         presult2 = eval.packet(presult2, k + 2 * PacketSize);
; 157  :         presult3 = eval.packet(presult3, k + 3 * PacketSize);
; 158  :       }
; 159  : 
; 160  :       if (numRemPackets >= 1) presult0 = eval.packet(presult0, quadEnd + 0 * PacketSize);

	cmp	r10, 1
	jb	SHORT $LN59@eigen_subt
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h

; 627  :   return _mm_mul_pd(a, b);

	movups	xmm1, XMMWORD PTR [rcx+rax*8]
	movups	xmm0, XMMWORD PTR [rdx+rax*8]
	mulpd	xmm1, xmm0

; 504  :   return _mm_add_pd(a, b);

	addpd	xmm2, xmm1
$LN59@eigen_subt:
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h

; 161  :       if (numRemPackets >= 2) presult1 = eval.packet(presult1, quadEnd + 1 * PacketSize);

	cmp	r10, 2
	jb	SHORT $LN60@eigen_subt
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h

; 627  :   return _mm_mul_pd(a, b);

	movups	xmm1, XMMWORD PTR [rcx+rax*8+16]
	movups	xmm0, XMMWORD PTR [rdx+rax*8+16]
	mulpd	xmm1, xmm0

; 504  :   return _mm_add_pd(a, b);

	addpd	xmm3, xmm1
$LN60@eigen_subt:
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h

; 162  :       if (numRemPackets == 3) presult2 = eval.packet(presult2, quadEnd + 2 * PacketSize);

	cmp	r10, 3
	jne	SHORT $LN61@eigen_subt
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h

; 627  :   return _mm_mul_pd(a, b);

	movups	xmm1, XMMWORD PTR [rcx+rax*8+32]
	movups	xmm0, XMMWORD PTR [rdx+rax*8+32]
	mulpd	xmm1, xmm0

; 504  :   return _mm_add_pd(a, b);

	addpd	xmm4, xmm1
$LN61@eigen_subt:
	addpd	xmm4, xmm5
	addpd	xmm3, xmm4
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h

; 121  :     for (Index k = 1; k < size; k++) {

	jmp	SHORT $LN341@eigen_subt
$LN58@eigen_subt:

; 167  :     if (numPackets >= 3) presult1 = padd(presult1, presult2);

	cmp	r9, 3
	jb	SHORT $LN62@eigen_subt
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h

; 504  :   return _mm_add_pd(a, b);

	addpd	xmm3, xmm4
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h

; 121  :     for (Index k = 1; k < size; k++) {

	jmp	SHORT $LN341@eigen_subt
$LN62@eigen_subt:

; 168  :     if (numPackets >= 2) presult0 = padd(presult0, presult1);

	cmp	r9, 2
	jb	SHORT $LN63@eigen_subt
$LN341@eigen_subt:
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h

; 504  :   return _mm_add_pd(a, b);

	addpd	xmm2, xmm3
$LN63@eigen_subt:
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\Reductions.h

; 270  :     tmp = Op::packetOp(a, _mm_unpackhi_pd(a, a));

	movaps	xmm4, xmm2
	unpckhpd xmm4, xmm2
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\arch\SSE\PacketMath.h

; 504  :   return _mm_add_pd(a, b);

	addpd	xmm4, xmm2
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h

; 171  :     for (UnsignedIndex k = packetEnd; k < size; k++) {

	cmp	r11, r8
	jae	$LN320@eigen_subt
	mov	rax, r8
	sub	rax, r11
	cmp	rax, 4
	jb	SHORT $LC321@eigen_subt
	mov	r10, r8
	lea	rax, QWORD PTR [rcx+8]
	sub	r10, r11
	lea	rax, QWORD PTR [rax+r11*8]
	sub	r10, 4
	mov	r9, rdx
	shr	r10, 2
	sub	r9, rcx
	inc	r10
	lea	r11, QWORD PTR [r11+r10*4]
	npad	9
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\CoreEvaluators.h

; 1256 :     return m_data[index * m_innerStride.value()];

$LL322@eigen_subt:
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\MathFunctions.h

; 1003 :     return x * y + z;

	movsd	xmm0, QWORD PTR [rax+r9]
	mulsd	xmm0, QWORD PTR [rax]
	movsd	xmm2, QWORD PTR [rax+r9-8]
	mulsd	xmm2, QWORD PTR [rax-8]
	movsd	xmm1, QWORD PTR [rax+r9+8]
	mulsd	xmm1, QWORD PTR [rax+8]
	addsd	xmm4, xmm2
	addsd	xmm4, xmm0
	movsd	xmm0, QWORD PTR [rax+r9+16]
	mulsd	xmm0, QWORD PTR [rax+16]
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h

; 172  :       result = eval.coeff(result, k);

	add	rax, 32					; 00000020H
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\MathFunctions.h

; 1003 :     return x * y + z;

	addsd	xmm4, xmm1
	addsd	xmm4, xmm0
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h

; 172  :       result = eval.coeff(result, k);

	sub	r10, 1
	jne	SHORT $LL322@eigen_subt

; 171  :     for (UnsignedIndex k = packetEnd; k < size; k++) {

	cmp	r11, r8
	jae	SHORT $LN320@eigen_subt
$LC321@eigen_subt:
	sub	rdx, rcx
	lea	rax, QWORD PTR [rcx+r11*8]
	sub	r8, r11
$LC335@eigen_subt:
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\MathFunctions.h

; 1003 :     return x * y + z;

	movsd	xmm0, QWORD PTR [rdx+rax]
	mulsd	xmm0, QWORD PTR [rax]
; File C:\Users\owner\Documents\git\kibo-linalg\.cache\eigen\Eigen\src\Core\InnerProduct.h

; 171  :     for (UnsignedIndex k = packetEnd; k < size; k++) {

	add	rax, 8

; 172  :       result = eval.coeff(result, k);

	addsd	xmm4, xmm0
	sub	r8, 1
	jne	SHORT $LC335@eigen_subt
$LN320@eigen_subt:
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\assembly-gap\kernels.cpp

; 12   :     return value-Eigen::Map<const Eigen::VectorXd,Eigen::Unaligned>(a,n).dot(Eigen::Map<const Eigen::VectorXd,Eigen::Unaligned>(b,n));

	subsd	xmm6, xmm4
	movaps	xmm0, xmm6

; 13   : }

	movaps	xmm6, XMMWORD PTR [rsp+16]
	add	rsp, 40					; 00000028H
	ret	0
eigen_subtract ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\assembly-gap\kernels.cpp
; File C:\Users\owner\Documents\git\kibo-linalg\include\kibo\detail\row_kernels.hpp
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\assembly-gap\kernels.cpp
; File C:\Users\owner\Documents\git\kibo-linalg\include\kibo\detail\row_kernels.hpp
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\assembly-gap\kernels.cpp
;	COMDAT packet_subtract
_TEXT	SEGMENT
a$ = 8
b$ = 16
n$ = 24
value$ = 32
packet_subtract PROC					; COMDAT

; 8    : extern "C" __declspec(noinline) double packet_subtract(const double* a,const double* b,std::size_t n,double value) {

$LN36:
	mov	QWORD PTR [rsp+8], rbx
; File C:\Users\owner\Documents\git\kibo-linalg\include\kibo\detail\row_kernels.hpp

; 241  :     auto first=_mm_setzero_pd(),second=first;

	mov	r9, rcx
	xor	r10d, r10d
	sub	r9, rdx
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\assembly-gap\kernels.cpp

; 8    : extern "C" __declspec(noinline) double packet_subtract(const double* a,const double* b,std::size_t n,double value) {

	mov	r11, rdx
	mov	rbx, rcx
	xorps	xmm4, xmm4
	xorps	xmm2, xmm2
; File C:\Users\owner\Documents\git\kibo-linalg\include\kibo\detail\row_kernels.hpp

; 242  :     for(;count-i>=4;i+=4) {

	cmp	r8, 4
	jb	SHORT $LN28@packet_sub

; 241  :     auto first=_mm_setzero_pd(),second=first;

	add	rdx, 16
$LL6@packet_sub:

; 243  :         first=_mm_add_pd(first,_mm_mul_pd(_mm_loadu_pd(left+i),_mm_loadu_pd(right+i)));

	movups	xmm0, XMMWORD PTR [rdx-16]
	add	r10, 4
	mov	rax, r8
	movups	xmm1, XMMWORD PTR [r9+rdx-16]
	sub	rax, r10
	mulpd	xmm1, xmm0

; 244  :         second=_mm_add_pd(second,_mm_mul_pd(_mm_loadu_pd(left+i+2),_mm_loadu_pd(right+i+2)));

	movups	xmm0, XMMWORD PTR [rdx]
	addpd	xmm4, xmm1
	movups	xmm1, XMMWORD PTR [r9+rdx]
	add	rdx, 32					; 00000020H
	mulpd	xmm1, xmm0
	addpd	xmm2, xmm1
	cmp	rax, 4
	jae	SHORT $LL6@packet_sub
$LN28@packet_sub:
	xorps	xmm0, xmm0

; 245  :     }
; 246  :     const auto total=_mm_add_pd(first,second);

	addpd	xmm2, xmm4

; 247  :     initial+=_mm_cvtsd_f64(total)+_mm_cvtsd_f64(_mm_unpackhi_pd(total,total));

	movaps	xmm1, xmm2
	unpckhpd xmm1, xmm2
	addsd	xmm1, xmm2
	addsd	xmm1, xmm0

; 248  : #endif
; 249  :     for(;i<count;++i) initial+=left[i]*right[i];

	cmp	r10, r8
	jae	$LN22@packet_sub
	mov	rax, r8
	sub	rax, r10
	cmp	rax, 4
	jb	SHORT $LC23@packet_sub
	mov	rcx, r8
	lea	rax, QWORD PTR [r11+8]
	sub	rcx, r10
	lea	rax, QWORD PTR [rax+r10*8]
	sub	rcx, 4
	shr	rcx, 2
	inc	rcx
	lea	r10, QWORD PTR [r10+rcx*4]
$LL24@packet_sub:
	movsd	xmm2, QWORD PTR [r9+rax-8]
	mulsd	xmm2, QWORD PTR [rax-8]
	movsd	xmm0, QWORD PTR [r9+rax]
	mulsd	xmm0, QWORD PTR [rax]
	addsd	xmm2, xmm1
	movsd	xmm1, QWORD PTR [r9+rax+8]
	mulsd	xmm1, QWORD PTR [rax+8]
	addsd	xmm2, xmm0
	addsd	xmm2, xmm1
	movsd	xmm1, QWORD PTR [r9+rax+16]
	mulsd	xmm1, QWORD PTR [rax+16]
	add	rax, 32					; 00000020H
	addsd	xmm1, xmm2
	sub	rcx, 1
	jne	SHORT $LL24@packet_sub
	mov	r9, rbx
	sub	r9, r11
$LC23@packet_sub:
	cmp	r10, r8
	jae	SHORT $LN22@packet_sub
	lea	rax, QWORD PTR [r11+r10*8]
	sub	r8, r10
$LC18@packet_sub:
	movsd	xmm0, QWORD PTR [r9+rax]
	mulsd	xmm0, QWORD PTR [rax]
	add	rax, 8
	addsd	xmm1, xmm0
	sub	r8, 1
	jne	SHORT $LC18@packet_sub
$LN22@packet_sub:
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\assembly-gap\kernels.cpp

; 10   : }

	mov	rbx, QWORD PTR [rsp+8]
	subsd	xmm3, xmm1
	movaps	xmm0, xmm3
	ret	0
packet_subtract ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\assembly-gap\kernels.cpp
;	COMDAT scalar_subtract
_TEXT	SEGMENT
a$ = 8
b$ = 16
n$ = 24
value$ = 32
scalar_subtract PROC					; COMDAT

; 4    : extern "C" __declspec(noinline) double scalar_subtract(const double* a,const double* b,std::size_t n,double value) {

	xor	r9d, r9d
	sub	rcx, rdx
	mov	r10, rdx

; 5    :     for(std::size_t k=0;k<n;++k)value-=a[k]*b[k];

	cmp	r8, 4
	jb	SHORT $LN17@scalar_sub
	lea	rax, QWORD PTR [rdx+8]
	lea	rdx, QWORD PTR [r8-4]
	shr	rdx, 2
	inc	rdx
	lea	r9, QWORD PTR [rdx*4]
	npad	10
$LL14@scalar_sub:
	movsd	xmm0, QWORD PTR [rcx+rax-8]
	mulsd	xmm0, QWORD PTR [rax-8]
	movsd	xmm1, QWORD PTR [rcx+rax]
	mulsd	xmm1, QWORD PTR [rax]
	subsd	xmm3, xmm0
	movsd	xmm0, QWORD PTR [rcx+rax+8]
	mulsd	xmm0, QWORD PTR [rax+8]
	subsd	xmm3, xmm1
	movsd	xmm1, QWORD PTR [rcx+rax+16]
	mulsd	xmm1, QWORD PTR [rax+16]
	add	rax, 32					; 00000020H
	subsd	xmm3, xmm0
	subsd	xmm3, xmm1
	sub	rdx, 1
	jne	SHORT $LL14@scalar_sub
$LN17@scalar_sub:
	cmp	r9, r8
	jae	SHORT $LN18@scalar_sub
	lea	rax, QWORD PTR [r10+r9*8]
	sub	r8, r9
$LC9@scalar_sub:
	movsd	xmm0, QWORD PTR [rcx+rax]
	mulsd	xmm0, QWORD PTR [rax]
	add	rax, 8
	subsd	xmm3, xmm0
	sub	r8, 1
	jne	SHORT $LC9@scalar_sub
$LN18@scalar_sub:

; 6    :     return value;
; 7    : }

	movaps	xmm0, xmm3
	ret	0
scalar_subtract ENDP
_TEXT	ENDS
END
