; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35222.0 

include listing.inc

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	_Avx2WmemEnabledWeakValue
;	COMDAT _Avx2WmemEnabledWeakValue
_BSS	SEGMENT
_Avx2WmemEnabledWeakValue DD 01H DUP (?)
_BSS	ENDS
PUBLIC	public_finite
PUBLIC	__real@7fefffffffffffff
PUBLIC	__xmm@7fffffffffffffff7fffffffffffffff
EXTRN	_fltused:DWORD
;	COMDAT __xmm@7fffffffffffffff7fffffffffffffff
CONST	SEGMENT
__xmm@7fffffffffffffff7fffffffffffffff DB 0ffH, 0ffH, 0ffH, 0ffH, 0ffH, 0ffH
	DB	0ffH, 07fH, 0ffH, 0ffH, 0ffH, 0ffH, 0ffH, 0ffH, 0ffH, 07fH
CONST	ENDS
;	COMDAT __real@7fefffffffffffff
CONST	SEGMENT
__real@7fefffffffffffff DQ 07fefffffffffffffr	; 1.79769e+308
CONST	ENDS
; Function compile flags: /Ogtpy
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\assembly-gap\public_assembly.cpp
; File C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.44.35207\include\cstdlib
; File C:\Users\owner\Documents\git\kibo-linalg\include\kibo\llt.hpp
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\assembly-gap\public_assembly.cpp
;	COMDAT public_finite
_TEXT	SEGMENT
value$ = 8
public_finite PROC					; COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.44.35207\include\cstdlib

; 24   :     return _CSTD fabs(_Xx);

	andps	xmm0, XMMWORD PTR __xmm@7fffffffffffffff7fffffffffffffff
; File C:\Users\owner\Documents\git\kibo-linalg\include\kibo\llt.hpp

; 25   :     return std::abs(value)<=std::numeric_limits<double>::max();

	movsd	xmm1, QWORD PTR __real@7fefffffffffffff
	comisd	xmm1, xmm0
	setae	al
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\assembly-gap\public_assembly.cpp

; 4    : }

	ret	0
public_finite ENDP
_TEXT	ENDS
END
