; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35222.0 

include listing.inc

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	_Avx2WmemEnabledWeakValue
;	COMDAT _Avx2WmemEnabledWeakValue
_BSS	SEGMENT
_Avx2WmemEnabledWeakValue DD 01H DUP (?)
_BSS	ENDS
PUBLIC	probe_column_dot
EXTRN	_fltused:DWORD
; Function compile flags: /Ogtpy
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\eigen-hardware-cause\assembly_probe.cpp
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\eigen-root-cause\qr\include\kibo\detail\row_kernels.hpp
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\eigen-hardware-cause\assembly_probe.cpp
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\eigen-root-cause\qr\include\kibo\detail\row_kernels.hpp
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\eigen-hardware-cause\assembly_probe.cpp
;	COMDAT probe_column_dot
_TEXT	SEGMENT
a$ = 8
b$ = 16
n$ = 24
probe_column_dot PROC					; COMDAT

; 3    :     return kibo::linalg::detail::contiguous_dot(a,b,n,0.0);

	xor	r9d, r9d
	sub	rcx, rdx
	mov	r10, rdx
	xorps	xmm2, xmm2
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\eigen-root-cause\qr\include\kibo\detail\row_kernels.hpp

; 261  :     for(;i<count;++i) initial+=left[i]*right[i];

	cmp	r8, 4
	jb	SHORT $LN18@probe_colu
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\eigen-hardware-cause\assembly_probe.cpp

; 3    :     return kibo::linalg::detail::contiguous_dot(a,b,n,0.0);

	lea	rax, QWORD PTR [rdx+8]
	lea	rdx, QWORD PTR [r8-4]
	shr	rdx, 2
	inc	rdx
	lea	r9, QWORD PTR [rdx*4]
	npad	7
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\eigen-root-cause\qr\include\kibo\detail\row_kernels.hpp

; 261  :     for(;i<count;++i) initial+=left[i]*right[i];

$LL15@probe_colu:
	movsd	xmm1, QWORD PTR [rcx+rax-8]
	mulsd	xmm1, QWORD PTR [rax-8]
	movsd	xmm0, QWORD PTR [rcx+rax]
	mulsd	xmm0, QWORD PTR [rax]
	addsd	xmm2, xmm1
	movsd	xmm1, QWORD PTR [rcx+rax+8]
	mulsd	xmm1, QWORD PTR [rax+8]
	addsd	xmm2, xmm0
	movsd	xmm0, QWORD PTR [rcx+rax+16]
	mulsd	xmm0, QWORD PTR [rax+16]
	add	rax, 32					; 00000020H
	addsd	xmm2, xmm1
	addsd	xmm2, xmm0
	sub	rdx, 1
	jne	SHORT $LL15@probe_colu
$LN18@probe_colu:
	cmp	r9, r8
	jae	SHORT $LN19@probe_colu
	lea	rax, QWORD PTR [r10+r9*8]
	sub	r8, r9
$LC6@probe_colu:
	movsd	xmm1, QWORD PTR [rax+rcx]
	mulsd	xmm1, QWORD PTR [rax]
	add	rax, 8
	addsd	xmm2, xmm1
	sub	r8, 1
	jne	SHORT $LC6@probe_colu
$LN19@probe_colu:
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\eigen-hardware-cause\assembly_probe.cpp

; 4    : }

	movaps	xmm0, xmm2
	ret	0
probe_column_dot ENDP
_TEXT	ENDS
END
