; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35222.0 

include listing.inc

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	_Avx2WmemEnabledWeakValue
;	COMDAT _Avx2WmemEnabledWeakValue
_BSS	SEGMENT
_Avx2WmemEnabledWeakValue DD 01H DUP (?)
_BSS	ENDS
PUBLIC	probe_column_dot
EXTRN	_fltused:DWORD
;	COMDAT pdata
pdata	SEGMENT
$pdata$?contiguous_dot@detail@linalg@kibo@@YANPEBN0_KN@Z DD imagerel $LN37
	DD	imagerel $LN37+283
	DD	imagerel $unwind$?contiguous_dot@detail@linalg@kibo@@YANPEBN0_KN@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$probe_column_dot DD imagerel $LN39
	DD	imagerel $LN39+285
	DD	imagerel $unwind$probe_column_dot
pdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$probe_column_dot DD 020501H
	DD	013405H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?contiguous_dot@detail@linalg@kibo@@YANPEBN0_KN@Z DD 020501H
	DD	013405H
xdata	ENDS
; Function compile flags: /Ogtpy
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\eigen-hardware-cause\assembly_probe.cpp
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\eigen-root-cause\qr\include\kibo\detail\row_kernels.hpp
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\eigen-hardware-cause\assembly_probe.cpp
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\eigen-root-cause\qr\include\kibo\detail\row_kernels.hpp
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\eigen-hardware-cause\assembly_probe.cpp
;	COMDAT probe_column_dot
_TEXT	SEGMENT
a$ = 8
b$ = 16
n$ = 24
probe_column_dot PROC					; COMDAT

; 2    : extern "C" __declspec(noinline) double probe_column_dot(const double* a,const double* b,std::size_t n){

$LN39:
	mov	QWORD PTR [rsp+8], rbx
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\eigen-root-cause\qr\include\kibo\detail\row_kernels.hpp

; 250  :     auto first=_mm_setzero_pd(),second=first;

	mov	r9, rcx
	xor	r10d, r10d
	sub	r9, rdx
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\eigen-hardware-cause\assembly_probe.cpp

; 2    : extern "C" __declspec(noinline) double probe_column_dot(const double* a,const double* b,std::size_t n){

	mov	r11, rdx
	mov	rbx, rcx
	xorps	xmm3, xmm3
	xorps	xmm2, xmm2
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\eigen-root-cause\qr\include\kibo\detail\row_kernels.hpp

; 251  :     for(;count-i>=4;i+=4) {

	cmp	r8, 4
	jb	SHORT $LN28@probe_colu

; 250  :     auto first=_mm_setzero_pd(),second=first;

	add	rdx, 16
$LL6@probe_colu:

; 252  :         first=_mm_add_pd(first,_mm_mul_pd(_mm_loadu_pd(left+i),_mm_loadu_pd(right+i)));

	movups	xmm0, XMMWORD PTR [rdx-16]
	add	r10, 4
	mov	rax, r8
	movups	xmm1, XMMWORD PTR [r9+rdx-16]
	sub	rax, r10
	mulpd	xmm1, xmm0

; 253  :         second=_mm_add_pd(second,_mm_mul_pd(_mm_loadu_pd(left+i+2),_mm_loadu_pd(right+i+2)));

	movups	xmm0, XMMWORD PTR [rdx]
	addpd	xmm3, xmm1
	movups	xmm1, XMMWORD PTR [r9+rdx]
	add	rdx, 32					; 00000020H
	mulpd	xmm1, xmm0
	addpd	xmm2, xmm1
	cmp	rax, 4
	jae	SHORT $LL6@probe_colu
$LN28@probe_colu:
	xorps	xmm0, xmm0

; 254  :     }
; 255  :     const auto total=_mm_add_pd(first,second);

	addpd	xmm2, xmm3

; 256  :     initial+=_mm_cvtsd_f64(total)+_mm_cvtsd_f64(_mm_unpackhi_pd(total,total));

	movaps	xmm3, xmm2
	unpckhpd xmm3, xmm2
	addsd	xmm3, xmm2
	addsd	xmm3, xmm0

; 257  : #endif
; 258  : #if defined(_MSC_VER) && defined(KIBO_QR_ABLATION_CPP_COLUMN)
; 259  : #pragma loop(no_vector)
; 260  : #endif
; 261  :     for(;i<count;++i) initial+=left[i]*right[i];

	cmp	r10, r8
	jae	$LN29@probe_colu
	mov	rax, r8
	sub	rax, r10
	cmp	rax, 4
	jb	SHORT $LC23@probe_colu
	mov	rcx, r8
	lea	rax, QWORD PTR [r11+8]
	sub	rcx, r10
	lea	rax, QWORD PTR [rax+r10*8]
	sub	rcx, 4
	shr	rcx, 2
	inc	rcx
	lea	r10, QWORD PTR [r10+rcx*4]
$LL24@probe_colu:
	movsd	xmm0, QWORD PTR [r9+rax]
	mulsd	xmm0, QWORD PTR [rax]
	movsd	xmm2, QWORD PTR [r9+rax-8]
	mulsd	xmm2, QWORD PTR [rax-8]
	movsd	xmm1, QWORD PTR [r9+rax+8]
	mulsd	xmm1, QWORD PTR [rax+8]
	addsd	xmm3, xmm2
	addsd	xmm3, xmm0
	movsd	xmm0, QWORD PTR [r9+rax+16]
	mulsd	xmm0, QWORD PTR [rax+16]
	add	rax, 32					; 00000020H
	addsd	xmm3, xmm1
	addsd	xmm3, xmm0
	sub	rcx, 1
	jne	SHORT $LL24@probe_colu
	mov	r9, rbx
	sub	r9, r11
$LC23@probe_colu:
	cmp	r10, r8
	jae	SHORT $LN29@probe_colu
	lea	rax, QWORD PTR [r11+r10*8]
	sub	r8, r10
$LC18@probe_colu:
	movsd	xmm1, QWORD PTR [r9+rax]
	mulsd	xmm1, QWORD PTR [rax]
	add	rax, 8
	addsd	xmm3, xmm1
	sub	r8, 1
	jne	SHORT $LC18@probe_colu
$LN29@probe_colu:
; File C:\Users\owner\Documents\git\kibo-linalg\tools\diagnostics\eigen-hardware-cause\assembly_probe.cpp

; 4    : }

	mov	rbx, QWORD PTR [rsp+8]
	movaps	xmm0, xmm3
	ret	0
probe_column_dot ENDP
_TEXT	ENDS
END
